### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by blksnk** [blksnk/font-compare#1]
- [ ] remove specific font from selection

- [ ] store store state in localstorage

- [ ] dark / light theme toggle

- [x] import local fonts

- [x] import fonts through url

- [ ] hide / show option sections, import forms, specific fonts
